### ISSUE TITLE
Crashing halfway through when attempting to update particles 

### ISSUE THREAD

**Issue by QuackCola** [rob5300/KeyValue3Updater#1]
Program is crashing halfway through at "-= Finished processing file thread (2/7)" while updating a set of imported l4d2 particles. Unknown why it is crashing now as the last time i ran it it went through without a problem.

**dump of console output -**
[logdump.txt](https://github.com/rob5300/KeyValue3Updater/files/8501537/logdump.txt)

**Comment by rob5300** [comment]
Thanks for this I can fix this soon. I was adding more updaters which probably caused this new issue.
