### ISSUE TITLE
Not updating all .vpcf files

### ISSUE THREAD

**Issue by QuackCola** [rob5300/KeyValue3Updater#3]
When running the updater on L4D2 vpcf Particle files the updater will pause at **_-= Finished processing file thread_** indefinitely with no error, thus not getting to half of the particle files. 

I've attached the particles in question in a zip archive to this issue to hopefully let you diagnose this particular issue. 

**Total Particle Files in particles folder before updating** 
1,818
**Total Particle Files in out/particles/ folder after updating** 
1,445

**Issue Screenshot:**
![InkedKeyValue3Updater_9o77rjNe7w_LI](https://user-images.githubusercontent.com/23345567/163725507-de14ae30-3e77-4ae8-93d3-7246aa553e51.jpg)

**Output Log Dump**
[outputdump.txt](https://github.com/rob5300/KeyValue3Updater/files/8502128/outputdump.txt)

**Particles in Question** 

[l4d2-vpcf-particles.zip](https://github.com/rob5300/KeyValue3Updater/files/8502105/l4d2-vpcf-particles.zip)

**Comment by rob5300** [comment]
From what I can tell, some expressions are taking an infinite amount of time on some files with only the "CParticleSystemDefinition" block. Ill add so these can time out to not hold up the whole program.

**Comment by rob5300** [comment]
Now fixed with v1.1.1
